RuleFile=/etc/usbguard/rules.conf
ImplicitPolicyTarget=block
PresentDevicePolicy=allow
InsertedDevicePolicy=apply-policy
PresentControllerPolicy=apply-policy
RestoreControllerDeviceState=false
DeviceManager=uevent
IPCAllowedUsers=root
IPCAllowedGroups=wheel
