[device]
wifi.backend=iwd
wifi.scan-rand-mac-address=yes

[main]
dns=systemd-resolved
plugins=keyfile

[connection]
wifi.powersave=2
wifi.cloned-mac-address=random
ethernet.cloned-mac-address=random

[connectivity]
enabled=false
uri=
interval=0
