#!/usr/bin/env bash
# Install official Helium Linux into an airootfs. Not AUR.
# Pin: channel/helium.lock (version + url + sha256).
set -euo pipefail
DEST="${1:?airootfs}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOCK="${ROOT}/channel/helium.lock"

[[ -f "${LOCK}" ]] || { echo "error: missing ${LOCK}" >&2; exit 1; }

version=""; url=""; sha256=""
while IFS='=' read -r k v; do
  [[ -z "${k}" || "${k}" == \#* ]] && continue
  case "${k}" in
    version) version="${v}" ;;
    url) url="${v}" ;;
    sha256) sha256="${v}" ;;
  esac
done < "${LOCK}"
[[ -n "${url}" && -n "${sha256}" ]] || { echo "error: helium.lock incomplete" >&2; exit 1; }

CACHE="${HELIUM_CACHE:-${CICADA_WORK:-/tmp}/helium-cache}"
mkdir -p "${CACHE}"
tarball="${CACHE}/helium-${version}-x86_64_linux.tar.xz"

echo "==> Helium ${version}"
if [[ -f "${tarball}" ]]; then
  got="$(sha256sum "${tarball}" | awk '{print $1}')"
  if [[ "${got}" != "${sha256}" ]]; then
    echo "==> cached tarball hash mismatch, re-downloading"
    rm -f "${tarball}"
  fi
fi
if [[ ! -f "${tarball}" ]]; then
  curl -fL --retry 3 -o "${tarball}.part" "${url}"
  mv "${tarball}.part" "${tarball}"
fi
got="$(sha256sum "${tarball}" | awk '{print $1}')"
if [[ "${got}" != "${sha256}" ]]; then
  echo "error: Helium sha256 ${got} != ${sha256}" >&2
  exit 1
fi

work="$(mktemp -d)"
trap 'rm -rf "${work}"' EXIT
tar -xJf "${tarball}" -C "${work}"

bin=""
while IFS= read -r cand; do
  bin="${cand}"
  break
done < <(find "${work}" -type f \( -name chrome -o -name helium -o -name helium-browser \) -print | sort)

[[ -n "${bin}" && -f "${bin}" ]] || { echo "error: no Helium binary in tarball" >&2; exit 1; }
srcdir="$(dirname "${bin}")"

rm -rf "${DEST}/opt/helium"
mkdir -p "${DEST}/opt"
cp -a "${srcdir}" "${DEST}/opt/helium"
chmod 755 "${DEST}/opt/helium"
# chrome_sandbox is unused under cicada-run (nested user ns off) but keep the bit.
if [[ -f "${DEST}/opt/helium/chrome_sandbox" ]]; then
  chmod 4755 "${DEST}/opt/helium/chrome_sandbox" || true
fi

relbin="$(basename "${bin}")"
mkdir -p "${DEST}/usr/bin"
ln -sfn "/opt/helium/${relbin}" "${DEST}/usr/bin/helium"
ln -sfn "/opt/helium/${relbin}" "${DEST}/usr/bin/helium-browser"

# --- keep the exec bits through mkarchiso -----------------------------------
# mkarchiso copies the profile airootfs with `cp -af --no-preserve=ownership,mode`
# and then re-applies modes ONLY for the paths listed in profiledef.sh's
# file_permissions. Nothing under /opt is listed there, so the browser binary
# shipped 0644: /usr/local/bin/chromium tests every candidate with `-x`, found
# none, and exited 1 — from a desktop click that is a Web icon that does
# nothing at all, with the error going to a stderr nobody reads.
#
# Collect every file that must stay executable, chmod it here (for non-archiso
# consumers such as install-chroot), and declare it to archiso as well.
declare -a helium_execs=()
for name in "${relbin}" helium chrome helium-wrapper chrome-wrapper \
            helium_crashpad_handler chrome_crashpad_handler chromedriver; do
  f="${DEST}/opt/helium/${name}"
  # -type f only: `chrome` is a symlink to the real binary, and chmod through a
  # symlink would silently apply to the target twice while the entry archiso
  # gets would be meaningless.
  [[ -f "${f}" && ! -L "${f}" ]] || continue
  # relbin is usually one of the literal names below; do not list it twice.
  printf '%s\n' ${helium_execs[@]+"${helium_execs[@]}"} | grep -Fxq "${name}" \
    || helium_execs+=("${name}")
done
while IFS= read -r f; do
  name="${f#"${DEST}/opt/helium/"}"
  [[ "${name}" == */* ]] && continue
  printf '%s\n' ${helium_execs[@]+"${helium_execs[@]}"} | grep -Fxq "${name}" \
    || helium_execs+=("${name}")
done < <(find "${DEST}/opt/helium" -maxdepth 1 -type f -perm -u+x)

# chrome_sandbox carries its own mode (4755, set above) and must not be flattened
# to 755 by the loop below — declare it separately so archiso restores the setuid
# bit rather than this script's default.
helium_setuid=""
for i in "${!helium_execs[@]}"; do
  if [[ "${helium_execs[i]}" == chrome_sandbox ]]; then
    helium_setuid=chrome_sandbox
    unset 'helium_execs[i]'
  fi
done
helium_execs=(${helium_execs[@]+"${helium_execs[@]}"})

for name in "${helium_execs[@]}"; do
  chmod 755 "${DEST}/opt/helium/${name}"
done

# profiledef.sh is one directory up when DEST is an archiso profile airootfs.
# Appending assignments (rather than editing the array literal) keeps this
# independent of assemble-profile.sh, which patches that literal by exact match.
profiledef="$(cd "${DEST}/.." 2>/dev/null && pwd)/profiledef.sh"
if [[ -f "${profiledef}" ]]; then
  {
    echo ""
    echo "# Helium exec bits — generated by scripts/install-helium.sh."
    echo "# mkarchiso copies airootfs with --no-preserve=mode; without these the"
    echo "# browser binary ships 0644 and the Web icon does nothing."
    for name in "${helium_execs[@]}"; do
      printf 'file_permissions["/opt/helium/%s"]="0:0:755"\n' "${name}"
    done
    if [[ -n "${helium_setuid}" ]]; then
      printf 'file_permissions["/opt/helium/%s"]="0:0:4755"\n' "${helium_setuid}"
    fi
  } >> "${profiledef}"
  echo "==> declared ${#helium_execs[@]} Helium exec bits in $(basename "${profiledef}")"
fi

# Helium reads Chromium-style enterprise policy from these trees.
for dest in \
  "${DEST}/etc/helium/policies" \
  "${DEST}/opt/helium/policies"
do
  mkdir -p "${dest}/managed" "${dest}/recommended"
  if [[ -d "${DEST}/etc/chromium/policies/managed" ]]; then
    cp -a "${DEST}/etc/chromium/policies/managed/." "${dest}/managed/"
  fi
  if [[ -d "${DEST}/etc/chromium/policies/recommended" ]]; then
    cp -a "${DEST}/etc/chromium/policies/recommended/." "${dest}/recommended/"
  fi
done

mkdir -p "${DEST}/etc/cicada"
printf '%s\n' "${version}" > "${DEST}/etc/cicada/helium.version"
echo "==> Helium ${version} -> /opt/helium (${relbin})"
