#!/usr/bin/env bash
# Install Chocolate Doom + Freedoom into an airootfs. Not AUR.
# Pin: channel/doom.lock (engine + IWAD urls + sha256).
# Built at ISO time on Arch (cmake + SDL2). Runtime needs sdl2/sdl2_mixer/sdl2_net.
set -euo pipefail
DEST="${1:?airootfs}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOCK="${ROOT}/channel/doom.lock"

[[ -f "${LOCK}" ]] || { echo "error: missing ${LOCK}" >&2; exit 1; }

engine_version=""; engine_url=""; engine_sha256=""
wad_version=""; wad_url=""; wad_sha256=""
while IFS='=' read -r k v; do
  [[ -z "${k}" || "${k}" == \#* ]] && continue
  case "${k}" in
    engine_version) engine_version="${v}" ;;
    engine_url) engine_url="${v}" ;;
    engine_sha256) engine_sha256="${v}" ;;
    wad_version) wad_version="${v}" ;;
    wad_url) wad_url="${v}" ;;
    wad_sha256) wad_sha256="${v}" ;;
  esac
done < "${LOCK}"
[[ -n "${engine_url}" && -n "${engine_sha256}" && -n "${wad_url}" && -n "${wad_sha256}" ]] \
  || { echo "error: doom.lock incomplete" >&2; exit 1; }

CACHE="${DOOM_CACHE:-${CICADA_WORK:-/tmp}/doom-cache}"
mkdir -p "${CACHE}"
engine_tar="${CACHE}/chocolate-doom-${engine_version}.tar.gz"
wad_zip="${CACHE}/freedoom-${wad_version}.zip"

fetch() {
  local url="$1" out="$2" want="$3"
  if [[ -f "${out}" ]]; then
    local got
    got="$(sha256sum "${out}" | awk '{print $1}')"
    if [[ "${got}" == "${want}" ]]; then
      return 0
    fi
    echo "==> cache hash mismatch for $(basename "${out}"), re-downloading"
    rm -f "${out}"
  fi
  curl -fL --retry 3 -o "${out}.part" "${url}"
  mv "${out}.part" "${out}"
  local got
  got="$(sha256sum "${out}" | awk '{print $1}')"
  if [[ "${got}" != "${want}" ]]; then
    echo "error: sha256 ${got} != ${want} for ${out}" >&2
    exit 1
  fi
}

echo "==> Freedoom ${wad_version} (IWAD)"
fetch "${wad_url}" "${wad_zip}" "${wad_sha256}"
wad_work="$(mktemp -d)"
unzip -q -o "${wad_zip}" -d "${wad_work}"
mkdir -p "${DEST}/usr/share/doom"
find "${wad_work}" -type f \( -iname 'freedoom1.wad' -o -iname 'freedoom2.wad' \) \
  -exec cp -a {} "${DEST}/usr/share/doom/" \;
[[ -f "${DEST}/usr/share/doom/freedoom1.wad" ]] || {
  echo "error: freedoom1.wad missing after extract" >&2
  exit 1
}
rm -rf "${wad_work}"

echo "==> Chocolate Doom ${engine_version} (build)"
if ! command -v cmake >/dev/null 2>&1; then
  echo "error: cmake required to build Chocolate Doom on the ISO builder" >&2
  exit 1
fi
for need in SDL2 SDL2_mixer SDL2_net; do
  if ! pkg-config --exists "${need}" 2>/dev/null \
     && ! pkg-config --exists "$(echo "${need}" | tr '[:upper:]' '[:lower:]')" 2>/dev/null; then
    # Headers may still exist via pacman -q; soft-check only.
    :
  fi
done

fetch "${engine_url}" "${engine_tar}" "${engine_sha256}"
eng_work="$(mktemp -d)"
tar -xzf "${engine_tar}" -C "${eng_work}"
src="$(find "${eng_work}" -maxdepth 1 -type d -name 'chocolate-doom*' | head -1)"
[[ -n "${src}" && -f "${src}/CMakeLists.txt" ]] || {
  echo "error: Chocolate Doom source tree missing CMakeLists.txt" >&2
  exit 1
}

cmake -S "${src}" -B "${src}/build" \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX=/opt/cicada-doom
cmake --build "${src}/build" -j"$(nproc 2>/dev/null || echo 2)"

# Upstream CMakeLists has no install() rules — cmake --install is a no-op.
# Copy the built game binary (and setup tool if present) ourselves.
doom_built="$(find "${src}/build" -type f -name 'chocolate-doom' -perm -u+x | head -1)"
[[ -n "${doom_built}" && -x "${doom_built}" ]] || {
  echo "error: chocolate-doom binary missing after cmake build" >&2
  find "${src}/build" -type f -name 'chocolate-*' 2>/dev/null | head -20 >&2 || true
  exit 1
}
mkdir -p "${DEST}/opt/cicada-doom/bin"
cp -a "${doom_built}" "${DEST}/opt/cicada-doom/bin/chocolate-doom"
chmod 755 "${DEST}/opt/cicada-doom/bin/chocolate-doom"
setup_built="$(find "${src}/build" -type f -name 'chocolate-setup' -perm -u+x | head -1 || true)"
if [[ -n "${setup_built}" && -x "${setup_built}" ]]; then
  cp -a "${setup_built}" "${DEST}/opt/cicada-doom/bin/chocolate-doom-setup"
  chmod 755 "${DEST}/opt/cicada-doom/bin/chocolate-doom-setup"
fi
rm -rf "${eng_work}"

bin="${DEST}/opt/cicada-doom/bin/chocolate-doom"
[[ -x "${bin}" ]] || { echo "error: chocolate-doom not installed at ${bin}" >&2; exit 1; }

mkdir -p "${DEST}/usr/bin"
ln -sfn /opt/cicada-doom/bin/chocolate-doom "${DEST}/usr/bin/chocolate-doom"
ln -sfn /usr/local/bin/cicada-doom "${DEST}/usr/bin/doom" 2>/dev/null || true

# mkarchiso strips modes unless listed in profiledef file_permissions.
profiledef="$(cd "${DEST}/.." 2>/dev/null && pwd)/profiledef.sh"
if [[ -f "${profiledef}" ]]; then
  {
    echo ""
    echo "# Chocolate Doom — generated by scripts/install-doom.sh."
    printf 'file_permissions["/opt/cicada-doom/bin/chocolate-doom"]="0:0:755"\n'
    if [[ -f "${DEST}/opt/cicada-doom/bin/chocolate-doom-setup" ]]; then
      printf 'file_permissions["/opt/cicada-doom/bin/chocolate-doom-setup"]="0:0:755"\n'
    fi
  } >> "${profiledef}"
fi

mkdir -p "${DEST}/etc/cicada"
printf 'engine=%s\nwad=%s\n' "${engine_version}" "${wad_version}" \
  > "${DEST}/etc/cicada/doom.version"
echo "==> Doom ready: /opt/cicada-doom + /usr/share/doom/freedoom*.wad"
